AWSTemplateFormatVersion: '2010-09-09'
Description: 'Dev Box Shared Resources - Route 53 Hosted Zone and Common Resources'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  
  DomainName:
    Type: String
    Default: yourdomain.com
    Description: Root domain name for the hosted zone
  
  CreateNewHostedZone:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Whether to create a new hosted zone or use existing
  
  ExistingHostedZoneId:
    Type: String
    Default: YOUR_HOSTED_ZONE_ID
    Description: Existing hosted zone ID to use

Resources:
  # Route 53 Hosted Zone (if creating new)
  HostedZone:
    Type: AWS::Route53::HostedZone
    Condition: CreateHostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub 'Hosted zone for ${Environment} dev box'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-dev-box-hosted-zone'
        - Key: Environment
          Value: !Ref Environment

  # Common IAM Policy for dev box access
  DevBoxCommonPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Common policies for dev box access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:dev-box-credentials*'
          - Effect: Allow
            Action:
              - ssm:SendCommand
              - ssm:ListCommandInvocations
              - ssm:DescribeInstanceInformation
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-dev-box-common-policy'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  HostedZoneId:
    Description: Route 53 Hosted Zone ID
    Value: !If 
      - CreateHostedZone
      - !Ref HostedZone
      - !Ref ExistingHostedZoneId
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'
  
  HostedZoneName:
    Description: Route 53 Hosted Zone name
    Value: !Ref DomainName
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneName'
  
  CommonPolicyArn:
    Description: ARN of the common IAM policy
    Value: !Ref DevBoxCommonPolicy
    Export:
      Name: !Sub '${AWS::StackName}-CommonPolicyArn'

Conditions:
  CreateHostedZone: !Equals [!Ref CreateNewHostedZone, 'true']